<h1><center>
------Milestone 2------
</h1></center>

<h2><center>
Nama  : Dendi Apriyandi

Batch : FTDS-005 (SBY) </h2></center>

Notebook ini dibuat untuk memprediksi cluster dan memastikan bahwa model yang disimpan berfungsi dan model dapat melakukan tugasnya dengan baik.

# **LIBRARIES**

In [1]:
import pickle  # Mengimpor modul pickle untuk serialisasi dan deserialisasi objek Python
import pandas as pd  # Mengimpor pandas, pustaka untuk manipulasi data dan analisis
import numpy as np  # Mengimpor numpy, pustaka untuk operasi numerik
import ast  # Mengimpor ast, modul untuk memanipulasi dan mengurai ekspresi kode Python

# **MODEL INFERENCE**

## Model Loading

In [2]:
with open('model_scaler.pkl', 'rb') as file_1:  # Membuka file 'model_scaler.pkl' dalam mode baca biner
    model_scaler = pickle.load(file_1)  # Memuat model_scaler dari file menggunakan pickle

with open('model_kmeans.pkl', 'rb') as file_2:  # Membuka file 'model_kmeans.pkl' dalam mode baca biner
    model_kmeans = pickle.load(file_2)  # Memuat model_kmeans dari file menggunakan pickle

with open('model_pca.pkl', 'rb') as file_3:  # Membuka file 'model_pca.pkl' dalam mode baca biner
    model_pca = pickle.load(file_3)  # Memuat model_pca dari file menggunakan pickle

## Creating Data Inference Dummy

In [3]:
# Membuat 11 data dummy
np.random.seed(1)  # Menetapkan seed untuk generator angka acak agar hasilnya dapat direproduksi

# Menghasilkan 11 angka acak yang uniform untuk setiap variabel berikut:
BALANCE = np.random.uniform(0, 18495, 11)  # Saldo
BALANCE_FREQUENCY = np.random.uniform(0, 1, 11)  # Frekuensi saldo
PURCHASES = np.random.uniform(0, 41050, 11)  # Pembelian
ONEOFF_PURCHASES = np.random.uniform(0, 40624, 11)  # Pembelian sekali
INSTALLMENTS_PURCHASES = np.random.uniform(0, 14686, 11)  # Pembelian cicilan
CASH_ADVANCE = np.random.uniform(0, 47137, 11)  # Uang muka tunai
PURCHASES_FREQUENCY = np.random.uniform(0, 1, 11)  # Frekuensi pembelian
ONEOFF_PURCHASES_FREQUENCY = np.random.uniform(0, 1, 11)  # Frekuensi pembelian sekali
PURCHASES_INSTALLMENTS_FREQUENCY = np.random.uniform(0, 1, 11)  # Frekuensi pembelian cicilan
CASH_ADVANCE_FREQUENCY = np.random.uniform(0, 1.5, 11)  # Frekuensi uang muka tunai
CASH_ADVANCE_TRX = np.random.uniform(0, 123, 11)  # Transaksi uang muka tunai
PURCHASES_TRX = np.random.uniform(0, 347, 11)  # Transaksi pembelian
CREDIT_LIMIT = np.random.uniform(50, 30000, 11)  # Batas kredit
PAYMENTS = np.random.uniform(0.049513, 50721, 11)  # Pembayaran
MINIMUM_PAYMENTS = np.random.uniform(0.019163, 76406, 11)  # Pembayaran minimum
PRC_FULL_PAYMENT = np.random.uniform(0, 1, 11)  # Persentase pembayaran penuh
TENURE = np.random.choice(['6', '7', '8', '9', '10', '11', '12'], 11)  # Masa jabatan

# Membuat DataFrame Inference
data_inf = pd.DataFrame({  # Membuat DataFrame menggunakan pandas
    'NAME' : 'Dendi',
    'BALANCE': BALANCE,  # Menetapkan kolom 'BALANCE' dengan data BALANCE
    'BALANCE_FREQUENCY': BALANCE_FREQUENCY,  # Menetapkan kolom 'BALANCE_FREQUENCY' dengan data BALANCE_FREQUENCY
    'PURCHASES': PURCHASES,  # Menetapkan kolom 'PURCHASES' dengan data PURCHASES
    'ONEOFF_PURCHASES': ONEOFF_PURCHASES,  # Menetapkan kolom 'ONEOFF_PURCHASES' dengan data ONEOFF_PURCHASES
    'INSTALLMENTS_PURCHASES': INSTALLMENTS_PURCHASES,  # Menetapkan kolom 'INSTALLMENTS_PURCHASES' dengan data INSTALLMENTS_PURCHASES
    'CASH_ADVANCE': CASH_ADVANCE,  # Menetapkan kolom 'CASH_ADVANCE' dengan data CASH_ADVANCE
    'PURCHASES_FREQUENCY': PURCHASES_FREQUENCY,  # Menetapkan kolom 'PURCHASES_FREQUENCY' dengan data PURCHASES_FREQUENCY
    'ONEOFF_PURCHASES_FREQUENCY': ONEOFF_PURCHASES_FREQUENCY,  # Menetapkan kolom 'ONEOFF_PURCHASES_FREQUENCY' dengan data ONEOFF_PURCHASES_FREQUENCY
    'PURCHASES_INSTALLMENTS_FREQUENCY': PURCHASES_INSTALLMENTS_FREQUENCY,  # Menetapkan kolom 'PURCHASES_INSTALLMENTS_FREQUENCY' dengan data PURCHASES_INSTALLMENTS_FREQUENCY
    'CASH_ADVANCE_FREQUENCY': CASH_ADVANCE_FREQUENCY,  # Menetapkan kolom 'CASH_ADVANCE_FREQUENCY' dengan data CASH_ADVANCE_FREQUENCY
    'CASH_ADVANCE_TRX': CASH_ADVANCE_TRX,  # Menetapkan kolom 'CASH_ADVANCE_TRX' dengan data CASH_ADVANCE_TRX
    'PURCHASES_TRX': PURCHASES_TRX,  # Menetapkan kolom 'PURCHASES_TRX' dengan data PURCHASES_TRX
    'CREDIT_LIMIT': CREDIT_LIMIT,  # Menetapkan kolom 'CREDIT_LIMIT' dengan data CREDIT_LIMIT
    'PAYMENTS': PAYMENTS,  # Menetapkan kolom 'PAYMENTS' dengan data PAYMENTS
    'MINIMUM_PAYMENTS': MINIMUM_PAYMENTS,  # Menetapkan kolom 'MINIMUM_PAYMENTS' dengan data MINIMUM_PAYMENTS
    'PRC_FULL_PAYMENT': PRC_FULL_PAYMENT,  # Menetapkan kolom 'PRC_FULL_PAYMENT' dengan data PRC_FULL_PAYMENT
    'TENURE': TENURE  # Menetapkan kolom 'TENURE' dengan data TENURE
})

data_inf  # Menampilkan DataFrame

,NAME,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,Dendi,7712.821977,0.685220,12866.062513,21659.306537,1515.977133,2515.350289,0.663795,0.347766,0.663441,0.925717,21.197883,9.095212,16852.855067,6154.704924,19279.215167,0.018576,12
1,Dendi,13322.401506,0.204452,28419.843373,28106.815877,6577.764325,27062.181570,0.514889,0.750812,0.621696,0.489967,16.867697,9.822351,608.486317,2259.763139,56832.763116,0.070022,7
2,Dendi,2.115362,0.878117,35975.774702,12817.506994,13343.633558,6916.344835,0.944595,0.725998,0.114746,0.790587,114.709242,85.435240,24028.948547,5452.253913,14932.000352,0.486345,9
3,Dendi,5591.640931,0.027388,36723.603537,27888.413686,4312.017383,27778.095093,0.586555,0.883306,0.949489,1.328913,85.708634,298.429698,7027.579502,11448.241701,44419.318220,0.606329,7
4,Dendi,2714.250201,0.670468,3491.064877,33905.833295,4226.268622,32984.509816,0.903402,0.623672,0.449912,0.535905,8.118021,186.974379,24222.800609,36163.528285,74115.347861,0.568851,10
5,Dendi,1707.802310,0.417305,1603.198852,742.942979,1909.599610,4823.737972,0.137475,0.750942,0.578390,1.362803,92.921955,191.829227,11666.426290,28389.426847,64702.804342,0.317362,12
6,Dendi,3444.882609,0.558690,6971.538723,30473.862650,284.423143,19517.357098,0.139276,0.348898,0.408137,0.935040,92.726771,292.184720,25913.078544,636.900761,18325.822452,0.988616,12
7,Dendi,6391.145647,0.140387,36047.749766,40171.492876,9969.378637,32731.940235,0.807391,0.269928,0.237027,0.023732,113.532018,43.088140,22426.293200,3650.653389,37726.978489,0.579745,7
8,Dendi,7338.214436,0.198101,4037.137529,30393.481544,3107.970512,19523.168228,0.397677,0.895886,0.903380,1.394156,87.517545,96.876737,16709.395008,49061.224354,47368.343901,0.380141,8
9,Dendi,9965.415495,0.800745,17286.468006,11392.756734,3899.818240,2354.656194,0.165354,0.428091,0.573679,1.036345,15.285328,203.258467,4136.834009,28814.644914,63339.117888,0.550948,11
10,Dendi,7753.002544,0.968262,39321.365213,32063.683439,7219.243417,25260.548886,0.927509,0.964840,0.002870,1.495984,2.445256,336.449725,1844.534801,10311.275603,11979.819458,0.745334,12

## SCALING

In [4]:
# Menghapus kolom 'TENURE' dari DataFrame dan menyimpannya sebagai data_inf_num
data_inf_num = data_inf.drop(columns=['NAME'])

In [5]:
# Menerapkan skala pada data_inf_num menggunakan model_scaler dan menyimpannya sebagai scaled_inf
scaled_inf = model_scaler.transform(data_inf_num)

## PCA

In [6]:
pca_inf = model_pca.transform(scaled_inf)  # Menerapkan PCA (Principal Component Analysis) pada scaled_inf menggunakan model_pca dan menyimpannya sebagai pca_inf
pca_inf  # Menampilkan hasil transformasi PCA

array([[ 2.81139184e-01,  8.90195568e-02, -2.87579273e-01,
        -8.43456810e-03,  8.35622350e-03,  8.21363786e-01,
         7.50522676e-02, -5.94896889e-03,  8.39272894e-02,
        -1.37710195e-01],
       [ 2.30346564e-01,  2.83376799e-01, -5.25517346e-03,
        -8.92254184e-01, -2.96834028e-01,  8.94832780e-01,
        -6.65106786e-02, -4.31577946e-01,  7.86471958e-01,
         1.32696555e-01],
       [ 3.99651296e-01,  7.34045733e-01,  1.67273121e-01,
        -4.56906507e-01,  3.54766316e-01,  8.52049133e-01,
         1.05960216e-02, -3.31231691e-02,  2.39660237e-01,
        -1.00577199e+00],
       [ 6.41217610e-01,  3.63132499e-01,  4.14173881e-01,
        -8.77386489e-01, -1.12057885e-01,  1.47028852e+00,
         4.00448594e-01, -8.88996825e-01,  6.04767093e-01,
        -4.20346871e-01],
       [ 5.58917240e-01,  5.23892196e-01,  2.51927312e-01,
        -2.46498153e-01,  1.56495922e-01,  9.88551871e-01,
        -2.42282718e-01, -5.30459106e-02,  3.66532379e-01,
        -6.49582825e-01],
       [-1.95395701e-03,  4.02708520e-01,  6.49801050e-02,
        -2.33147243e-02, -1.00745193e-02,  1.13112362e+00,
         5.69457093e-01, -6.31774990e-01,  3.67419855e-02,
        -2.24375489e-01],
       [-2.60750639e-03,  3.19658702e-01,  6.53753023e-01,
         1.93891230e-01,  3.82852118e-01,  1.24434032e+00,
         7.96369049e-02, -3.71842634e-01, -4.82969320e-04,
        -3.82931763e-01],
       [ 2.33033438e-01,  2.17190835e-01,  5.63938641e-01,
        -7.31374651e-01, -1.22364607e-01,  1.16276169e+00,
        -3.65473107e-01,  9.21142313e-02,  6.39494608e-01,
        -7.28763816e-01],
       [ 3.94072494e-01,  3.93495563e-01,  1.42316564e-01,
        -6.90915991e-01,  7.65245707e-03,  1.60192359e+00,
         3.36557339e-01, -6.32832479e-01,  2.09384165e-01,
        -3.10194683e-01],
       [ 5.62113123e-02,  1.99194106e-01,  1.57754048e-01,
        -3.73417935e-02,  3.89923886e-01,  8.77681016e-01,
         9.26258799e-02, -6.58038579e-01,  6.57881994e-01,
        -1.24495043e-01],
       [ 4.46127420e-01,  1.09070485e+00,  1.89535280e-01,
        -3.96647951e-02,  4.81562536e-01,  8.02728693e-01,
         4.18093317e-01, -4.19743560e-01,  1.03042254e+00,
        -7.21617647e-01]])

## PREDICTING

In [7]:
# Prediksi pada Inference-Set

cluster_inf = model_kmeans.predict(pca_inf)  # Memprediksi cluster untuk data pca_inf menggunakan model_kmeans dan menyimpannya sebagai cluster_inf
cluster_inf  # Menampilkan hasil prediksi cluster

array([1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0])

In [8]:
# Konversi ke dalam DataFrame

cluster_inf_df = pd.DataFrame(cluster_inf, columns=['Cluster - Prediction'])  # Membuat DataFrame dari cluster_inf dengan kolom 'Cluster - Prediction'
cluster_inf_df  # Menampilkan DataFrame hasil prediksi cluster

    Cluster - Prediction
0                      1
1                      0
2                      0
3                      0
4                      0
5                      0
6                      2
7                      0
8                      0
9                      0
10                     0

In [9]:
# Menggabungkan Inference-Set dan Prediksi

tabel_inference = pd.concat([data_inf, cluster_inf_df], axis=1)  # Menggabungkan data_inf dan cluster_inf_df secara horizontal (axis=1) dan menyimpannya sebagai tabel_inference
tabel_inference  # Menampilkan tabel_inference hasil penggabungan

,NAME,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE,Cluster - Prediction
0,Dendi,7712.821977,0.685220,12866.062513,21659.306537,1515.977133,2515.350289,0.663795,0.347766,0.663441,0.925717,21.197883,9.095212,16852.855067,6154.704924,19279.215167,0.018576,12,1
1,Dendi,13322.401506,0.204452,28419.843373,28106.815877,6577.764325,27062.181570,0.514889,0.750812,0.621696,0.489967,16.867697,9.822351,608.486317,2259.763139,56832.763116,0.070022,7,0
2,Dendi,2.115362,0.878117,35975.774702,12817.506994,13343.633558,6916.344835,0.944595,0.725998,0.114746,0.790587,114.709242,85.435240,24028.948547,5452.253913,14932.000352,0.486345,9,0
3,Dendi,5591.640931,0.027388,36723.603537,27888.413686,4312.017383,27778.095093,0.586555,0.883306,0.949489,1.328913,85.708634,298.429698,7027.579502,11448.241701,44419.318220,0.606329,7,0
4,Dendi,2714.250201,0.670468,3491.064877,33905.833295,4226.268622,32984.509816,0.903402,0.623672,0.449912,0.535905,8.118021,186.974379,24222.800609,36163.528285,74115.347861,0.568851,10,0
5,Dendi,1707.802310,0.417305,1603.198852,742.942979,1909.599610,4823.737972,0.137475,0.750942,0.578390,1.362803,92.921955,191.829227,11666.426290,28389.426847,64702.804342,0.317362,12,0
6,Dendi,3444.882609,0.558690,6971.538723,30473.862650,284.423143,19517.357098,0.139276,0.348898,0.408137,0.935040,92.726771,292.184720,25913.078544,636.900761,18325.822452,0.988616,12,2
7,Dendi,6391.145647,0.140387,36047.749766,40171.492876,9969.378637,32731.940235,0.807391,0.269928,0.237027,0.023732,113.532018,43.088140,22426.293200,3650.653389,37726.978489,0.579745,7,0
8,Dendi,7338.214436,0.198101,4037.137529,30393.481544,3107.970512,19523.168228,0.397677,0.895886,0.903380,1.394156,87.517545,96.876737,16709.395008,49061.224354,47368.343901,0.380141,8,0
9,Dendi,9965.415495,0.800745,17286.468006,11392.756734,3899.818240,2354.656194,0.165354,0.428091,0.573679,1.036345,15.285328,203.258467,4136.834009,28814.644914,63339.117888,0.550948,11,0
10,Dendi,7753.002544,0.968262,39321.365213,32063.683439,7219.243417,25260.548886,0.927509,0.964840,0.002870,1.495984,2.445256,336.449725,1844.534801,10311.275603,11979.819458,0.745334,12,0